/// Created by Be <be@mixxx.org> and A. Colombier <mixxx@acolombier.dev>

import { S5 } from './s5';

/* eslint no-unused-vars: "off", no-var: "off" */
export var TraktorS5 = new S5({
  fxUnitLeft: {
    knobs: [
      {
        touch: { inByte: 3, inBit: 3, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
      },
      {
        touch: { inByte: 3, inBit: 2, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
      },
      {
        touch: { inByte: 3, inBit: 1, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
      },
      {
        touch: { inByte: 3, inBit: 0, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
      },
    ],
    buttons: [
      { inByte: 5, inBit: 2, inLengthBit: 1, outByte: 0 },
      { inByte: 5, inBit: 5, inLengthBit: 1, outByte: 0 },
      { inByte: 5, inBit: 3, inLengthBit: 1, outByte: 0 },
      { inByte: 5, inBit: 4, inLengthBit: 1, outByte: 0 },
    ],
  },
  deckLeft: {
    displayAreaAndControls: {
      settings: { inByte: 7, inBit: 6, inLengthBit: 1, outByte: 0 },
      display1: { inByte: 7, inBit: 1, inLengthBit: 1, outByte: 0 },
      display2: { inByte: 7, inBit: 7, inLengthBit: 1, outByte: 0 },
      performanceMode1: { inByte: 7, inBit: 0, inLengthBit: 1, outByte: 0 },
      view: { inByte: 6, inBit: 4, inLengthBit: 1, outByte: 0 },
      display3: { inByte: 6, inBit: 3, inLengthBit: 1, outByte: 0 },
      display4: { inByte: 6, inBit: 5, inLengthBit: 1, outByte: 0 },
      performanceMode2: { inByte: 6, inLengthBit: 1, inBit: 2, outByte: 0 },
    },
    browseControls: {
      browse: {
        touch: { inByte: 13, inBit: 4, inLengthBit: 1 },
        press: { inByte: 6, inBit: 1, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 4 },
      },
      back: { inByte: 6, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    modeSelect: {
      hotcue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      freeze: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      remix: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    pads: [
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    ],
    transportControls: {
      shift: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      sync: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      play: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    flux: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    loop: {
      touch: { inByte: 0, inBit: 0, inLengthBit: 1 },
      press: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    deck: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
  },
  mixer: {
    channelC: {
      gain: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fxUnit1Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      fxUnit2Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      eqHigh: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqMid: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqLow: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filter: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filterBtn: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      volume: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    channelA: {
      gain: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fxUnit1Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      fxUnit2Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      eqHigh: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqMid: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqLow: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filter: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filterBtn: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      volume: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    mainVol: { inByte: 0, inBit: 0, inLengthBit: 1 },
    snap: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    quantize: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    boothVol: { inByte: 0, inBit: 0, inLengthBit: 1 },
    tempoEncoder: {
      touch: { inByte: 0, inBit: 0, inLengthBit: 1 },
      press: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    cueMix: { inByte: 0, inBit: 0, inLengthBit: 1 },
    cueVol: { inByte: 0, inBit: 0, inLengthBit: 1 },
    aux: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    auxToggle: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    channelB: {
      gain: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fxUnit1Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      fxUnit2Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      eqHigh: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqMid: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqLow: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filter: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filterBtn: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      volume: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    channelD: {
      gain: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fxUnit1Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      fxUnit2Assign: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      eqHigh: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqMid: { inByte: 0, inBit: 0, inLengthBit: 1 },
      eqLow: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filter: { inByte: 0, inBit: 0, inLengthBit: 1 },
      filterBtn: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      volume: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    cross: { inByte: 0, inBit: 0, inLengthBit: 1 },
  },
  fxUnitRight: {
    knobs: [
      { inByte: 0, inBit: 0, inLengthBit: 1 },
      { inByte: 0, inBit: 0, inLengthBit: 1 },
      { inByte: 0, inBit: 0, inLengthBit: 1 },
      { inByte: 0, inBit: 0, inLengthBit: 1 },
    ],
    buttons: [
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    ],
  },
  deckRight: {
    displayAreaAndControls: {
      settings: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      display1: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      display2: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      performanceMode1: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      view: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      display3: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      display4: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      performanceMode2: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    browseControls: {
      browse: {
        touch: { inByte: 0, inBit: 0, inLengthBit: 1 },
        press: { inByte: 0, inBit: 0, inLengthBit: 1 },
        fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
      },
      back: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    modeSelect: {
      hotcue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      freeze: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      remix: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    pads: [
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    ],
    transportControls: {
      shift: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      sync: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      cue: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
      play: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    },
    flux: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
    loop: {
      touch: { inByte: 0, inBit: 0, inLengthBit: 1 },
      press: { inByte: 0, inBit: 0, inLengthBit: 1 },
      fade: { inByte: 0, inBit: 0, inLengthBit: 1 },
    },
    deck: { inByte: 0, inBit: 0, inLengthBit: 1, outByte: 0 },
  },
});
